[supervisord]
nodaemon=true
user=root
pidfile=/tmp/supervisord.pid
logfile=/tmp/supervisord.log

[program:xvfb]
# 16-bit color depth saves immense CPU cycle calculations and RAM
command=Xvfb :1 -screen 0 1024x768x16
autorestart=true
redirect_stderr=true
stdout_logfile=/tmp/xvfb.log

[program:openbox]
# Openbox is an ultra-fast window manager that uses almost 0% CPU at idle
command=openbox-session
autorestart=true
environment=DISPLAY=":1",HOME="/tmp"
redirect_stderr=true
stdout_logfile=/tmp/openbox.log

[program:x11vnc]
# High-speed rendering options passed to x11vnc
command=x11vnc -forever -shared -rfbport 5900 -display :1 -nopw -noshm
autorestart=true
redirect_stderr=true
stdout_logfile=/tmp/x11vnc.log

[program:novnc]
command=websockify --web /usr/share/novnc %(env(PORT))s localhost:5900
autorestart=true
redirect_stderr=true
stdout_logfile=/tmp/novnc.log
