[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:sshd]
command=/usr/sbin/sshd -D
autorestart=true

[program:xvfb]
command=Xvfb :1 -screen 0 1280x720x24
autorestart=true

[program:x11vnc]
command=x11vnc -display :1 -nopw -listen 0.0.0.0 -forever -shared
autorestart=true
depends_on=xvfb

[program:xrdp-sesman]
command=/usr/sbin/xrdp-sesman --nodaemon
autorestart=true

[program:xrdp]
command=/usr/sbin/xrdp --nodaemon
autorestart=true
depends_on=xrdp-sesman

[program:xfce4]
command=display=:1 startxfce4
environment=DISPLAY=":1"
autorestart=true
depends_on=xvfb
