[supervisord]
nodaemon=true
user=root
pidfile=/tmp/supervisord.pid
logfile=/tmp/supervisord.log

[program:xvfb]
# Reduced resolution and 16-bit color depth saves immense RAM
command=Xvfb :1 -screen 0 1024x768x16
autorestart=true
redirect_stderr=true
stdout_logfile=/tmp/xvfb.log

[program:xfce4]
command=startxfce4
autorestart=true
environment=DISPLAY=":1",HOME="/tmp"
redirect_stderr=true
stdout_logfile=/tmp/xfce4.log

[program:x11vnc]
command=x11vnc -forever -shared -rfbport 5900 -display :1 -nopw
autorestart=true
redirect_stderr=true
stdout_logfile=/tmp/x11vnc.log

[program:novnc]
command=websockify --web /usr/share/novnc %(env(PORT))s localhost:5900
autorestart=true
redirect_stderr=true
stdout_logfile=/tmp/novnc.log
